#!/usr/bin/env python3
#
# Lenovo-derived: copies the physical keyboard strings of the stock Lenovo
# settings app (ZuiSettings.apk, ZUI 17.5) into
# parts/res/values*/strings_lenovo_keyboard.xml, prefixed with "lkb_".
#
# Usage: lenovo_keyboard_strings.py [path/to/ZuiSettings.apk]
import os, re, subprocess, sys

HERE = os.path.dirname(os.path.abspath(__file__))
RES = os.path.join(HERE, '..', 'parts', 'res')
TOP = os.path.abspath(os.path.join(HERE, '..', '..', '..', '..'))
AAPT = os.path.join(TOP, 'out', 'host', 'linux-x86', 'bin', 'aapt2')
APK = sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser(
    '~/tb520fu/system/priv-app/ZuiSettings/ZuiSettings.apk')

KEYS = [
    'physical_keyboard_title', 'keyboard_assistance_category',
    'folio_case_mode', 'folio_case_mode_summary',
    'keyboard_shortcuts_helper', 'keyboard_shortcuts_summary', 'keyboard_shortcuts_switch',
    'modifier_keys_settings', 'modifier_keys_settings_summary',
    'keyboard_auto_brightness', 'keyboard_auto_brightness_summary',
    'keyboard_repeat_keys_title', 'keyboard_repeat_keys_summary', 'keyboard_a11y_settings',
    'keyboard_a11y_category', 'sticky_keys', 'sticky_keys_summary', 'bounce_keys',
    'slow_keys', 'mouse_keys', 'mouse_keys_summary',
    'physical_keyboard_touchpad', 'physical_keyboard_single_finger_touch',
    'touch_or_swipe_wake_title', 'keyboard_keyboard_touch_bright_screen_summary',
    'trackpad_bottom_right_tap_title', 'trackpad_bottom_right_tap_summary',
    'trackpad_reverse_scrolling_title', 'trackpad_reverse_scrolling_summary2',
    'physical_keyboard_pointer', 'pointer_speed',
    'keyboard_shortcut_application_key', 'keyboard_shortcut_application_key_app1',
    'keyboard_shortcut_application_key_app2', 'keyboard_shortcut_application_tips',
    'keyboard_app_shortcut_option_launch_app_or_shortcut',
    'keyboard_app_shortcut_option_launch_app_or_shortcut_summary',
    'keyboard_app_shortcut_option_open_url', 'keyboard_app_shortcut_option_open_url_summary',
    'keyboard_app_shortcut_option_set_url', 'keyboard_app_shortcut_option_set_url_hint',
    'solid_state_upgrade', 'keyboard_tips',
    'pc_mode_keyboard_connect_system_mode', 'screen_cast_phone_mode_title',
    'pc_mode_settings_title_name',
] + ['keyboard_shortcuts_switch_title_%d' % i for i in range(1, 22)] \
  + ['keyboard_shortcuts_switch_summary_%d' % i for i in range(1, 21)]

# Stock locale -> our values dir suffix (default: same)
LOCALE_DIR = {'es-rUS': 'es'}

# Stock translations that are wrong: most locales translate the "Settings"
# shortcut (Action + I) as "Done"; use the Settings app name instead.
SOURCE = {'keyboard_shortcuts_switch_title_11': 'settings_label'}


def dump():
    out = subprocess.run([AAPT, 'dump', 'resources', APK], capture_output=True,
                         text=True, check=True).stdout.splitlines()
    data, cur = {}, None
    for line in out:
        m = re.match(r'\s*resource 0x[0-9a-f]+ string/(\S+)', line)
        if m:
            name = m.group(1)
            cur = next((k for k, src in SOURCE.items() if src == name), None)
            if cur is None and name in KEYS and name not in SOURCE:
                cur = name
            if cur:
                data[cur] = {}
            continue
        if re.match(r'\s*resource ', line):
            cur = None
            continue
        if cur:
            m = re.match(r'\s*\(([^)]*)\) (?:\(styled string\) )?"(.*)"\s*$', line)
            if m:
                data[cur][m.group(1)] = m.group(2)
    return data


def xml_escape(s):
    s = s.replace('\\"', '"').replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
    s = s.replace("\\'", "'").replace("'", "\\'").replace('"', '\\"')
    if s.startswith(('@', '?')):
        s = '\\' + s
    return s


def main():
    data = dump()
    missing = [k for k in KEYS if k not in data or '' not in data[k]]
    if missing:
        sys.exit('missing default strings: %s' % missing)
    locales = sorted({loc for v in data.values() for loc in v})
    for loc in locales:
        if loc.startswith('en-rX'):  # pseudo-locales
            continue
        d = LOCALE_DIR.get(loc, loc)
        values = 'values' + ('-' + d if d else '')
        rows = []
        for k in KEYS:
            v = data[k].get(loc)
            if v is None or (loc and v == data[k]['']):
                continue
            rows.append('    <string name="lkb_%s">%s</string>\n' % (k, xml_escape(v)))
        if not rows:
            continue
        os.makedirs(os.path.join(RES, values), exist_ok=True)
        with open(os.path.join(RES, values, 'strings_lenovo_keyboard.xml'), 'w') as f:
            f.write('<?xml version="1.0" encoding="utf-8"?>\n'
                    '<!-- Lenovo-derived: generated by tools/lenovo_keyboard_strings.py'
                    ' from the stock ZuiSettings.apk. Do not edit. -->\n'
                    '<resources xmlns:tools="http://schemas.android.com/tools"'
                    ' tools:ignore="MissingTranslation">\n')
            f.writelines(rows)
            f.write('</resources>\n')
    print('locales:', len(locales))


if __name__ == '__main__':
    main()
